### ISSUE TITLE
GameJolt.batch() Invalid call. Nonexistent function 'percent_encode' in base 'String'

### ISSUE THREAD

**Issue by Tiredness-Games** [murikistudio/game-jolt-api#4]
I may be missing something, but when trying to do a GameJolt.batch() it gives me the following error: Invalid call. Nonexistent function 'percent_encode' in base 'String'

The following is what throws the error:

`GameJolt.batch_begin()`
`for key in blank_title_keys[keys]:`
`	GameJolt.data_store_fetch(key["key"], true)`
`GameJolt.batch_end()`
`GameJolt.batch()`

![image](https://github.com/murikistudio/game-jolt-api/assets/81962875/15dda1b8-99d1-4688-8e8b-37b4edfc4b25)

**Comment by joelgomes1994** [comment]
@Tiredness-Games Hello, thanks for the report! That's something I ended up overlooking in the upgrade from Godot 3.x to 4.x of the addon, I'm sorry. For a quick fix, just replace `percent_encode` with `uri_encode`. I will upload a fix to the asset library as soon as possible.

**Comment by joelgomes1994** [comment]
I just fixed the issue, you can find the updated version on the releases page. Again, thanks for the report! :pray: 

https://github.com/murikistudio/game-jolt-api/releases/tag/v0.0.5

**Comment by Tiredness-Games** [comment]
Thanks for the quick reply and fix!
